Feature/simcom
wirenboard/modemmanager pull request #2
Opened 2022-07-25 11:36 UTC by KraPete

Патчи для поддержки SIM A7600E-H:
1. Поправил разбор ответа на `AT+CGDCONT?`. Старый регэксп расчитывал, что есть минимум 4 параметра в ответе. По стандарту можно меньше. Наш модем присылает 3. В результате не работала процедура проверки того, что контекст создан.
2. Убрал `-Werror`. Вылезла куча мест, где компилятор ругается на преобразование выравнивания (`Wcast-align`). Возможно, надо как-то иначе собирать, но я не понял как. `dpkg-buildpackage -us -uc` приводит к этим ошибкам, без них всё собирается и работает.
3. MM запрашивает у модема типы IP адресов, которые тот поддерживает. Модем возвращает ошибку, если не зареган в сети. К сожалению, эта процедура выполняется один раз за всё время, и результат потом кэшируется. Получается так, что MM не видит ни одного типа IP адресов. При создании поключения NetworkManager офигевает от такого расклада и падает в сегфолт. Отдаю для SIM A7600E-H все возможные типы без запроса к модему.

2022-07-25 12:11 UTC, evgeny-boger requested changes
нам же эти два патча надо отправлять в апстрим. 

Поэтому нужно:
1) от первого оторвать коммит в наш debian/changelog
2) перенести из описания PR подробное описание проблемы в commit message
3) отправить это как патчи в апстрим

2022-07-25 12:22 UTC, KraPete commented
> нам же эти два патча надо отправлять в апстрим.
> 
> Поэтому нужно:
> 
>     1. от первого оторвать коммит в наш debian/changelog
> 
>     2. перенести из описания PR подробное описание проблемы в commit message
> 
>     3. отправить это как патчи в апстрим

Не уверен, что всё могут принять. Как минимум последний патч - скорее костыль. Думаю, надо менять логику запроса списка поддерживаемых типов IP, т.е. делать это где-то в другом месте или иначе. Это субъективно переделывание внутренней логики MM. Оно нам надо? Плюс в bullseye сейчас версии MM и NM не из upstream.

2022-07-25 13:19 UTC, evgeny-boger commented
ну конечно надо, потому что иначе тебе придётся это раз в полгода натягивать на новый modemanager, а это быстро надоест. Можно отправить как есть, заодно кто-нибудь расскажет как это сделать правильно.

2022-08-05 13:43 UTC, KraPete commented
@evgeny-boger @webconn Последни коммитом добавил переключение симок чрезе стандартные команды MM
![изображение](https://user-images.githubusercontent.com/86825564/183088862-bc4e656e-0b52-4e13-8187-b6acaadd74fd.png)

Код в части работы с gpio - полное г. Основной вопрос в том, как мы будем передавать в MM информацию, что у нас есть 2 слота, и какой gpio за это всё отвечает. Сейчас MM умеет читать настройки из udev, т.е. правилом добавляются параметры в устройство, и MM их вычитывает. Предлагаю сделать аналогично. Можно при старте генерить правило, с нужным номером gpio.

2022-08-10 06:46 UTC, KraPete commented
Сделал переключение симки через libgpiod. Добавил параметр `ID_MM_SIM_SWITCH_GPIO_LABEL` с меткой gpio, чтобы сигнализировать MM о том, как переключать симки.
Пример правила для A7600E-H, которое объявляет такое gpio:
```
ATTRS{idVendor}=="1e0e", ATTRS{idProduct}=="9011", ENV{ID_MM_SIM_SWITCH_GPIO_LABEL}="SIM_SELECT"
```

2022-09-08 13:05 UTC, webconn commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
Этот метод не по умолчанию разве? Я так понимаю, он скопипащен

2022-09-08 13:05 UTC, webconn commented on plugins/simtech/mm-broadband-modem-simtech.c
> +    /* Longer entries first so we catch the correct one with strcmp() */
Они же сравниваются не `strcmp()`, а `g_str_has_prefix()`, вот тогда становится понятно, почему тут это важно

2022-09-08 13:05 UTC, webconn commented on plugins/simtech/mm-broadband-modem-simtech.c
> +/* Load sim slots (Modem interface) */
Комментарий несколько раз повторяется

2022-09-08 13:05 UTC, webconn commented on src/mm-base-sim.c
> +        20,
Так критичен оказался этот таймаут?

2022-09-08 13:07 UTC, webconn commented
И как в итоге с патчами? Проводить ревью у нас в этом плане смысла не очень много, лучше сразу забросить это в сообщество. Если с нашей стороны сейчас всё работает, надо мержить, а потом по мере принятия патчей переносить то, что не примут никогда

2022-09-08 13:19 UTC, KraPete commented on src/mm-base-sim.c
> +        20,
Yes! У меня локально буквально секунды не хватало. В доке у симкома ничего не написано про таймаут, так что увеличил в 2 раза с запасом

2022-09-08 13:20 UTC, webconn commented on src/mm-base-sim.c
> +        20,
Жуть. Меня смущает, что это в общем коде тут происходит, и об этом никак не догадаешься. Хочу комментарий в этом месте, и запись в changelog, что мы это сделали осознанно

2022-09-08 13:20 UTC, KraPete commented
> И как в итоге с патчами? Проводить ревью у нас в этом плане смысла не очень много, лучше сразу забросить это в сообщество. Если с нашей стороны сейчас всё работает, надо мержить, а потом по мере принятия патчей переносить то, что не примут никогда

Я бы довёл всё до нашего testing, поправил всё, что вылезет на широкой публике, и потом начал патчи слать.

2022-09-08 13:25 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
Да. Я посмотрел как остальные плагины сделаны, там тоже копируют, вот и перенёс.

2022-09-08 13:28 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +/* Load sim slots (Modem interface) */
Исправил

2022-09-08 13:28 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +    /* Longer entries first so we catch the correct one with strcmp() */
Убрал вообще

2022-09-08 13:29 UTC, webconn commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
Вот этот метод вроде никто не копировал... Его по наследству никак не получить?

2022-09-08 13:30 UTC, KraPete commented on src/mm-base-sim.c
> +        20,
Можно утащить это всё в плагин. Будет гора копипасты ради одной константы.

2022-09-08 13:31 UTC, webconn commented on src/mm-base-sim.c
> +        20,
Не, давай не будем, просто подпишем, что это место хрупкое

2022-09-08 13:32 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
Обычно делают пару `запрос-finish`. Можно из `iface_modem_parent` взять

2022-09-08 13:32 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
Опасность в том, что поменяется логика метода в родителе, и тут мы ничего не узнаем.

2022-09-08 13:33 UTC, webconn commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
Ну тут же finish полностью идентичен, вряд ли есть смысл копипастить

2022-09-08 13:34 UTC, webconn commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
> Опасность в том, что поменяется логика метода в родителе, и тут мы ничего не узнаем.

Если от смены логики в родителе что-то будет зависеть, всё и так наверняка на нашем коде сломается, потому что только мы его и поддерживаем

2022-09-08 13:39 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
Я имел ввиду логику `запрос-finish`. Сигнатура запроса и `finish` задана в интерфейсе, она не изменится. `finish` интерпретирует промежуточный результат запроса и выдаёт что-то вызвавшему. И вот этот промежуточный результат - особенность реализации. Он может измениться, и finish у родителя тоже.

2022-09-08 13:47 UTC, webconn commented on plugins/simtech/mm-broadband-modem-simtech.c
> +load_supported_ip_families_finish (MMIfaceModem *self,
Ладно, давай оставим это как есть.

2022-09-08 13:47 UTC, webconn requested changes

2022-09-08 13:47 UTC, webconn commented on src/mm-base-sim.c
> +        20,
Всё ещё актуально

2022-09-14 11:04 UTC, KraPete commented on src/mm-base-sim.c
> +        20,
Я по коду посмотрел, в других местах при вызове этой команды уже стоит 20 секунд таймаута. Просто тут забыли. Может, не писать комменты? А то придётся и в остальных местах добавлять.

2022-09-14 12:48 UTC, webconn commented on src/mm-base-sim.c
> +        20,
А в других-то зачем? Смысл этих комментариев в том, чтобы обозначить наши собственные изменения. Может пригодиться, если в апстриме тоже поменяют, будет чуть проще дифф читать

2022-09-16 05:15 UTC, KraPete commented on src/mm-base-sim.c
> +        20,
Написал

2022-09-16 07:34 UTC, webconn approved these changes

2022-09-19 10:37 UTC, KraPete commented
Rebase https://github.com/wirenboard/modemmanager/pull/3

2022-09-19 10:37 UTC, closed without merging