Feature/upstream update
wirenboard/modemmanager pull request #6
Opened 2022-10-28 12:28 UTC by KraPete

В bullseye-backports заехал новый MM, портировал на него наши изменения

2022-10-28 14:56 UTC, webconn commented on Jenkinsfile
> +	       defaultWbdevImage: 'contactless/devenv_lp',
Вот эту опцию можно выносить

2022-10-28 14:56 UTC, webconn commented on Jenkinsfile
> +	       defaultWbdevInstallDeps: 'yes',
Эту тоже после https://github.com/wirenboard/jenkins-pipeline-lib/pull/24 (уже влито)

2022-10-28 15:16 UTC, KraPete commented on Jenkinsfile
> +	       defaultWbdevImage: 'contactless/devenv_lp',
Убрал

2022-10-28 15:16 UTC, KraPete commented on Jenkinsfile
> +	       defaultWbdevInstallDeps: 'yes',
Убрал

2022-10-28 15:22 UTC, lostpoint-ru commented on Jenkinsfile
> +	       defaultWbdevInstallDeps: 'yes',
defaultWbdevInstallDeps: 'yes',

вот это, по идее, тоже можно убирать -- захардкодили же.

2022-10-28 15:23 UTC, lostpoint-ru commented on Jenkinsfile
> +	       defaultWbdevInstallDeps: 'yes',
а, всё, вижу, уже выпилили :)

2022-10-28 15:28 UTC, lostpoint-ru commented on m4/ax_is_release.m4
> +        AS_IF([test -d ${srcdir}/.git],[ax_is_release=yes],[ax_is_release=yes])
Вот эта правка убьёт нам сборку в дженкинсе. 

Я специально подкостылил в этом месте чтобы оно собиралось даже при наличии папки .git

2022-10-28 15:30 UTC, lostpoint-ru requested changes
Правку в [m4/ax_is_release.m4] надо откатить (ну или придумать более элегантный способ избежать появления -Werror при сборке с существующей папкой .git)

UPD. Проглючило, всё ок с правкой.

2022-10-28 15:33 UTC, lostpoint-ru commented on m4/ax_is_release.m4
> +        AS_IF([test -d ${srcdir}/.git],[ax_is_release=yes],[ax_is_release=yes])
Тьфу, совсем заработался. Сначала показалось что это откат нашей правки.

2022-10-28 15:34 UTC, lostpoint-ru approved these changes

2022-10-28 15:37 UTC, sikmir approved these changes

2022-10-31 06:41 UTC, webconn approved these changes

2022-10-31 06:42 UTC, merged