Feature/60532 modem restart
wirenboard/modemmanager pull request #8
Opened 2023-04-20 21:30 UTC by vdromanov

если требуемый primary_slot уже выбран - не переключаем его, чтобы модем не перезагружался

проверял через mmcli -m any --set-primary-sim-slot + minicom в модем в соседнем окне

2023-04-21 04:07 UTC, KraPete requested changes
Ты сделал локальную проверку внутри mmcli. Если, переключать через dbus, то проверки нет. Я ж писал в задаче, где надо исправить.

2023-04-24 18:09 UTC, vdromanov commented
теперь поправил

2023-04-25 04:58 UTC, KraPete requested changes

2023-04-25 04:58 UTC, KraPete commented on cli/mmcli-modem.c
> +
Можно убрать, чтоб изменения не плодить

2023-04-25 04:58 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +            MmGdbusModem *skeleton;
Я таки предлагаю смотреть на состояние GPIO, как в `mm_broadband_modem_simtech_load_sim_slots_finish`

2023-04-25 10:02 UTC, vdromanov commented on plugins/simtech/mm-broadband-modem-simtech.c
> +            MmGdbusModem *skeleton;
готово!

2023-04-25 10:02 UTC, vdromanov commented on cli/mmcli-modem.c
> +
готово

2023-04-25 10:20 UTC, KraPete requested changes

2023-04-25 10:20 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +            current_primary_slot = get_gpio_line_value (gpio_label, self) + 1;
Тут надо в самом начале `gpiod_line_close_chip (line);` и из `else` убрать

2023-04-25 12:06 UTC, vdromanov commented on plugins/simtech/mm-broadband-modem-simtech.c
> +            current_primary_slot = get_gpio_line_value (gpio_label, self) + 1;
готово!

2023-04-25 13:01 UTC, KraPete requested changes

2023-04-25 13:01 UTC, KraPete commented on plugins/simtech/mm-broadband-modem-simtech.c
> +            current_primary_slot = get_gpio_line_value (gpio_label, self) + 1;
Ну нет же. Надо сначала освободить линию, потом запрашивать значение. Внутри функции со значением линия снова запрашивается.

2023-04-25 14:43 UTC, vdromanov commented on plugins/simtech/mm-broadband-modem-simtech.c
> +            current_primary_slot = get_gpio_line_value (gpio_label, self) + 1;
fixed

2023-04-26 04:35 UTC, KraPete approved these changes

2023-04-26 07:45 UTC, merged